services:
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./data_pg:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
  ingest:
    build:
      context: ./
      dockerfile: ./Dockerfile 
    container_name: ingest_data
    command:
      - /bin/bash
      - -c
      - |
        python ingest_data.py --user=admin \
          --password=admin \
          --host=pgdatabase \
          --port=5432 \
          --db=ny_taxi \
          --table_name=yellow_taxi_trips \
          --url=${URL_YELLOW}
        python ingest_data.py --user=admin \
          --password=admin \
          --host=pgdatabase \
          --port=5432 \
          --db=ny_taxi \
          --table_name=green_taxi_trips \
          --url=${URL_GREEN}
        python ingest_data.py --user=admin \
          --password=admin \
          --host=pgdatabase \
          --port=5432 \
          --db=ny_taxi \
          --table_name=zones \
          --url=${URL_ZONES}
    depends_on:
      - pgdatabase
